In [1]:
def compute():
    try:
        a = 5/0
    except Exception as e:
        print(e)
        print('Exception handled')

compute()

division by zero
Exception handled


In [2]:
print('*'*30)

subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for i in subjects:
    for j in verbs:
        for k in objects:
            print(f"{i} {j} {k}")

print('*'*30)
s = [(a , b , c)  for a in subjects for b in verbs for c in objects]
for item in s:
    print(f'{item[0]}  {item[1]} {item[2]}')
#s = [i for i in subjects]

print('*'*30)

******************************
Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket
******************************
Americans   play Baseball
Americans   play Cricket
Americans   watch Baseball
Americans   watch Cricket
Indians  play Baseball
Indians  play Cricket
Indians  watch Baseball
Indians  watch Cricket
******************************


In [1]:
l = [1,2,3,4]

n = int(input("Enter nof columns :"))

re = []
import numpy as np

for a in l:
    for b in range(1,n+1):
        re.append(a**b)
print("re1 -->",re)
print(np.array(re).reshape(len(l),-1))

re2 = []
for a in l:
    for b in range(n, 0 , -1):
        re2.append(a**b)
print("re2 -->",re2)
print(np.array(re2).reshape(len(l),-1))


Enter nof columns :4
re1 --> [1, 1, 1, 1, 2, 4, 8, 16, 3, 9, 27, 81, 4, 16, 64, 256]
[[  1   1   1   1]
 [  2   4   8  16]
 [  3   9  27  81]
 [  4  16  64 256]]
re2 --> [1, 1, 1, 1, 16, 8, 4, 2, 81, 27, 9, 3, 256, 64, 16, 4]
[[  1   1   1   1]
 [ 16   8   4   2]
 [ 81  27   9   3]
 [256  64  16   4]]
