Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [4]:
import numpy as np
def vandermonde1(l,n,boolean):
    if boolean:
        vandermonde = np.array([x**i for x in l  for i in range(n)]).reshape(l.size,n)
    else:
        vandermonde = np.array([x**(n-1-i) for x in l for i in range(n)]).reshape(l.size,n)
    return vandermonde
li = np.array([1,2,3,4])
k = 4
o_matrix_inc_order = vandermonde1(li,k,True)
o_matrix_dec_order = vandermonde1(li,k,False)
print('list : ', li , ' and k value is :', k)
print('\no_matrix_inc_order : \n', o_matrix_inc_order)
print('\no_matrix_dec_order : \n', o_matrix_dec_order)

list :  [1 2 3 4]  and k value is : 4

o_matrix_inc_order : 
 [[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]

o_matrix_dec_order : 
 [[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [11]:
def movingAverage(li, k):
    n = li.size
    l1 = []
    for i in range(n-k+1):
        l1.append(np.mean([li[i:i+k]]))
    
    return l1

l = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
k = 4
print('The list of items : ', l , ' and window value is : ',k)
print('\nThe moving Average list is :\n\n',movingAverage(l,k))
        
l2 =  np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k2 = 3

print('\n**************************\n')
print('The list of items : ', l2 , ' and window value is : ',k2)
print('\nThe moving Average list is : \n\n',movingAverage(l2,k2))

The list of items :  [ 10  20  30  40  50  60  70  80  90 100]  and window value is :  4

The moving Average list is :

 [25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]

**************************

The list of items :  [  3   5   7   2   8  10  11  65  72  81  99 100 150]  and window value is :  3

The moving Average list is : 

 [5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
